### PR TITLE
refactor(ts): warn on missing module boundary return types instead of throwing errors

### PR DESCRIPTION
**Pull request by crabl**
Remove the error for module boundary return types, and use a non-blocking warning instead.

**See the documentation of the rule**: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md

**Code that would be rejected**: An exported function without an explicit return type.
**Code that would be accepted**: An exported function with an explicit return type.

Local functions not exported out of a module file are not included in this rule.

### CODE REVIEW

**Comment by matt-forster** [comment]
https://github.com/autovance/style/pull/20

**Comment by matt-forster** [comment]
There have been previous debates (#20) around this - and I think the way to go is to continue using errors and put the iterative work up front. It ends up being a much more robust pattern for changes and creates a significantly better typing environment for future development.

**Comment by matt-forster** [comment]
@autovance/developers (especially @autovance/front), please weigh in on this change and let us know so we can move forward with the styling.

**Comment by iamart** [comment]
I can see how refactoring a module can break the code where the module is being used but wouldn't the typescript throw a type error during compile (especially in strict mode)?
I don't have strong preference to warn or error, at least at this point.

**Comment by matt-forster** [comment]
Only during compile - a lot of instant feedback is gained when you have the types defined. How often do you run the compiler locally against every file affected by the implicitly mutated return type?

**Comment by iamart** [comment]
Well since we have multiple projects, refactoring engine and testing compilation of desk only might lead to myDeal being broken. CI would prevent this from going into production but I agree the instant feedback would be nice.

**Comment by millerjb** [comment]
I definitely agree with @matt-forster both here and in his comments on #20. Allowing implied types in exported functions offers you some rope that seems to allow only hanging yourself. What is actually _gained_ by allowing implicitly typed exports? @crabl's initial comment explains the change, but fails to offer an argument for it.

**Comment by matt-forster** [comment]
@autovance/developers - We are closing this because we have come to the conclusion that this is a valuable global rule, and can be dealt with for repos on an individual basis.

**Pull request closed without merging**
