### PR TITLE
refactor(ts): allow TypeScript namespaces

### PR DESCRIPTION
**Pull request by crabl**
## Background

Inside of the platform repo we use TypeScript namespaces to organize Action and Selector modules.

## Alternative 1: Use classes with static members to organize modules
https://github.com/autovance/platform/compare/static-class-member-exports

## Alternative 2: Use ES6 modules
https://github.com/autovance/platform/compare/es6-module-exports

Drawbacks:

Using `import * as ...` means that the programmer is responsible for:
1. remembering the import syntax
2. assigning the correct name to the import, and 
3. not selectively importing individual selectors into the file

It also makes the modules more difficult to refactor because you'd have to do a find-and-replace for all instances of `DepositSelectors` instead of renaming the symbol.

### CODE REVIEW

**Comment by matt-forster** [comment]
I'm a fan of the modules, because the change is really just limited to the import statements - and it cleans up the actual definitions significantly, where the work would be done most of the time.

But, I am ok merging this, and perhaps if the team wants to revisit it later, we can reference this PR.

**Comment by matt-forster** [comment]
@autovance/developers (especially @autovance/front), please weigh in on what you would like to see here, and then we will move forward.

**Comment by iamart** [comment]
I'm slightly leaning towards es6 modules; but both solutions seem fine to me.
Not really sure why we should abstain from individual selector import though w/ modules (alt 2, drawback 3).

@matt-forster can you explain how modules clean up the definitions significantly? from my understanding it's only `namespace {}` lines going away.

**Comment by matt-forster** [comment]
Yes, if you look at the diff - it's the indentation and additional export that goes away. In my humble opinion, additional indentation is something we can always try to avoid. Having the exports in their own context on each line just makes more sense to me, and I can read it.

https://github.com/autovance/platform/blob/ac8eb8a5a7c6f2c027c720ee6ce10909dd6540ad/packages/engine/deposit/deposit.selectors.ts

vs.

https://github.com/autovance/platform/blob/master/packages/engine/deposit/deposit.selectors.ts

I am also unsure why the individual pattern is avoided throughout all of the files where, if I understand it correctly, the naming is only an issue in the import file for debugging.

**Comment by millerjb** [comment]
Coming from a background where I worked frequently in .NET the class w/ static member approach is more familiar to me.

That said, I don't have a _strong_ preference. You can put me down as opposite @iamart, slightly leaning to classes but both are fine. 🙃

**Comment by iamart** [comment]
Approving means we continue to use namespaces. The main reason we still use namespaces is probeSelector() I believe, which lets you to see the selector's state in production.

**Review by matt-forster — APPROVED** [review]

**Review by oksana-autovance — APPROVED** [review]
I agree with @crabl on possible drawbacks  using ES6 modules for our project, that's why I'm ok with the following changes.

**Review by iamart — APPROVED** [review]

**Pull request merged**
