### PR TITLE
Merge pull request #10 from autovance/disallow-promise-catch

### PR DESCRIPTION
**Pull request by trs**
Indicates a `.catch()` call as a warning to use async/await instead.

This is implemented as an override as `no-restricted-syntax` cannot mix warnings and errors.

### CODE REVIEW

**Comment by forstermatth** [comment]
Does this achieve interoperability with the current restrictions, or just overwrite them? Perhaps they can all be warnings?

**Comment by forstermatth** [comment]
Does this achieve interopability with the current restrictions, or just overwrite them?

**Comment by trs** [comment]
Yeah looks like this overwrites them.

**Pull request merged**
